### PR TITLE
Bootstrap 5 upgrade

### PR DESCRIPTION
**Pull request by treborin**
I there,
This is the beginning to move on from the old Bootstrap 3 UI up to the recent Bootstrap 5 (5.2.2). Version 5 brings a lot of new visual tool for a very nice user experience, but first i'm using what we have now with version 3, and later on will use new tools step by step.
This process requires a huge amount of changes, not only over the .tpl files, but also many .js, specially for the validations process.
I need more time to finish everything, but here is what i have done right now. Hope someone could test and contribute.
I'm thinking about to add a new var in config file (something like $conf['settings']['bootstrap.ver'] = '5';) for letting anyone to choose any of both, '5' or '3'. I's easy to modify header file in order to do that.
You'll find a new develop-bs5 branch to send PRs.

NOTE: i'm working on this on weekends and free time, so be patient

### CODE REVIEW

**Comment by labmecanicatec** [comment]
Hello everyone, we want to participate in completing the migration to Bootstrap 5, how can we contribute to this project? We have cloned this branch and applied the changes to the develop branch, the results have been encouraging but as mentioned, this process requires a lot of changes. We are working with Bootstrap 5.3 and Bootstrap Icons 1.11.
Captura de pantalla 2023-12-27 091326
Captura de pantalla 2023-12-27 091404
Captura de pantalla 2023-12-27 092314
Captura de pantalla 2023-12-27 092339
Captura de pantalla 2023-12-27 092434
Captura de pantalla 2023-12-27 092513

**Comment by treborin** [comment]
Hi @labmecanicatec ,
That's good news. 
What i have done is to create my own brand (boostrap5) inside my Librebooking fork, here: [https://github.com/treborin/LibreBooking/tree/bootstrap5](url)
From there, you can propose as many PRs as you need, and @effgarces will check and merge them.
I've been too busy and overwhelmed. My plan is to take this up again next 2024, but in the same way, on weekends and free time.
Here I am for any collaboration proposal.

**Comment by labmecanicatec** [comment]
Hello @treborin,

Our plan is to integrate your work into our branch and complement it. While we finish, we could discuss certain design ideas, for example, integrating a font like Roboto or Hind, or evaluating the possibility of simplifying the booked.css file so that later the administrator can customize the color scheme. When we have a significant progress, we'll agree on how we can share the code for corrections, and when the result is satisfactory, we'll submit the PR to LibreBooking/app.
Captura de pantalla 2023-12-29 192150

**Comment by treborin** [comment]
Great! You can use Gitter to contact developers here:
[https://app.gitter.im/#/room/#bookedscheduler_development:gitter.im](url)

Gracias por colaborar :)

**Comment by F0r3n5iC-Sw33t13** [comment]
Is it correct that the Gitter URL not work?

**Comment by treborin** [comment]
Sorry, @F0r3n5iC-Sw33t13,
This is the right one: https://app.gitter.im/#/room/#bookedscheduler_development:gitter.im

**Comment by labmecanicatec** [comment]
Captura de pantalla 2024-02-14 104814
Captura de pantalla 2024-02-14 105152
Captura de pantalla 2024-02-14 105215
@treborin, the project advances!

**Comment by labmecanicatec** [comment]
Hi @treborin , 
We want to inform that the project continues, but there are still things to fix or improve, because this project is quite complex we have not made any PR, but we want to start a review process, so we invite you and all those interested in reviewing the progress of the project, it is available in [our repository](https://github.com/labmecanicatec/app). We appreciate all the comments you can give us, but we emphasize that it is not yet fully functional.

**Comment by treborin** [comment]
Hi, @labmecanicatec ,

I asked @effgarces to open develop-bs5 branch for this purpose. This is the easiest way for anyone to access all changes people cand make. Just send your PR's there and @effgarces will check and accept them.
We could use gitter too. There, we can open private (only you and me, for instance)/public rooms. I think that using this PR is not the right place to comunicate.

If no unforeseen events, next week i'm going to spend two or three days checking everything and will be in touch soon.
Maybe we can see what we need and how to resolve. I know it´s a complex task

**Comment by labmecanicatec** [comment]
It seems good to us, on Monday we will do the PR, we need to rest... We like the idea of ​​creating a room in Gitter, it would not help to have a more personal communication and in this way we could discuss the proposals we have made about the appearance, the parts of code where we need help, etc.

**Comment by labmecanicatec** [comment]
Hi @treborin ,
I created a room at https://app.gitter.im/ so we can chat about this project.

**Pull request merged**
